version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    env_file:
      - .env

    ports:
      - "9090:8000"   # LOCAL:CONTAINER

    restart: always

    mem_limit: 1g
    cpus: 2.0
